### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by rafhuys-klarrio** [markirch/sat-modulo-symmetries#23]
I've installed Boost and CaDiCal. When running `./build-and-install.sh` (Cmake 3.27.7) I get:

```
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/raf/Projects/vub/dmos/sat-modulo-symmetries/build

--SMS-- build-and-install.sh: building SMS

[  6%] Building CXX object src/CMakeFiles/sms.dir/minimalityCheck.cpp.o
[  6%] Building CXX object src/CMakeFiles/smsdir.dir/minimalityCheck_dir.cpp.o
In file included from /home/raf/Projects/vub/dmos/sat-modulo-symmetries/src/minimalityCheck.hpp:5,
                 from /home/raf/Projects/vub/dmos/sat-modulo-symmetries/src/minimalityCheck_dir.cpp:1:
/home/raf/Projects/vub/dmos/sat-modulo-symmetries/src/graphChecker.hpp:20:5: error: ‘uint64_t’ does not name a type
   20 |     uint64_t limit_reached = 0;    // count calls which did not provide a conclusive answer
      |     ^~~~~~~~
/home/raf/Projects/vub/dmos/sat-modulo-symmetries/src/graphChecker.hpp:8:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    7 | #include <iomanip>
  +++ |+#include <cstdint>
    8 |

```

Any idea what I'm missing?

**Comment by rafhuys-klarrio** [comment]
had to do 
```

**Comment by markirch** [comment]
Thanks for the input. Can you tell me which c++ compiler are you currently using?

It also might be possible that adding ` #include <cstdint> `  to the file graphChecker.h, since this is the only file using the mentioned datatype. This was also mentioned from the compiler as a potential solution, i.e.,
/home/raf/Projects/vub/dmos/sat-modulo-symmetries/src/graphChecker.hpp:8:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    7 | #include <iomanip>
  +++ |+#include <cstdint>
    8 |

**Comment by peitl** [comment]
Can you tell us which OS and compiler you are using? I can build fine with GCC 11.4 on Ubuntu 22.04, this might be a matter of older compilers/standards having to include the `<cstdint>` header, which is not necessary in newer versions. Perhaps we also incorrectly specified the required standard, but if you could provide more information about your setup that would be appreciated.

**Comment by rafhuys-klarrio** [comment]
I'm on a fairly new version though: `gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)` on Fedora 38. Anyway, the changes above do allow me to run sms without issues it seems, so I'm happy to close this issue

**Comment by peitl** [comment]
Thanks, it might be a too-new rather than too-old version issue. According to [https://gcc.gnu.org/gcc-13/porting_to.html](https://gcc.gnu.org/gcc-13/porting_to.html), the internal header dependencies in GCC 13 have changes, and this results in missing includes in code that used to work fine. Thanks for reporting, hopefully this will be useful for others who run into the same issue.
